Implicit Predicate Atom
dgopstein/atom-finder pull request #12
Opened 2017-04-13 17:21 UTC by jakeinc

I'm not sure if my tests were done properly.
  I noticed how when I run lein test it doesn't specify my atom (it also doesn't specify omitted-curly-braces).

2017-04-14 03:47 UTC, dgopstein requested changes
This is great Jake! There are couple features missing, but this code is 90% of the way there.

These comments start with the important ones, and get less significant as the list goes on:

- Currently your code classifies `if (!(x == y));` as an atom, but I don't think it ought to.
- I don't think you included a complete list of predicate contexts, i.e. places where predicates are used. Can you think of a way find an exhaustive list?
- Every time we make a new atom classifier we need to add it to the list in classifiers.clj before it'll get used in analyses. Would you mind putting this in there?

2017-04-14 03:47 UTC, dgopstein commented on src/atom_finder/classifier/implicit-predicate.clj
> +(def logical-operators #{IASTBinaryExpression/op_equals
This list looks like it might be useful in other contexts as well. Could you put this in classifier_util.clj??

2017-04-14 03:47 UTC, dgopstein commented on src/atom_finder/classifier/implicit-predicate.clj
> +(defn implicit-preciate-for-if-statement?
`preciate` is misspelled.

2017-04-14 03:47 UTC, dgopstein commented on src/atom_finder/classifier/implicit-predicate.clj
> +    :else true))
`implicit-predicate-while-do-loop?` and `implicit-preciate-for-if-statement` are basically identical, and they both throw exceptions if you pass in the wrong type. I think you can fix both issues by moving the `.getConditionExpression`/`.getCondition` outside the function into the calling code

2017-04-14 03:47 UTC, dgopstein commented on src/atom_finder/classifier/implicit-predicate.clj
> +   :else false))
If you wanted you could refactor this to use `some` or `atom-finder.util/any-pred` instead of `cond`, and it would reduce a little bit of repetition.

2017-05-01 18:52 UTC, jakeinc commented
Hey Dan,
I still feel like my code doesn't have the functional "style", but I made some of the corrections you requested. What do you think?
-Jake

2017-05-02 02:45 UTC, dgopstein reviewed
The key to functional programming is composition. Writing general functions that you can reuse in multiple places, then combining them together. This goes hand-in-hand with the “single-responsibility-principle” which is to say that every function should do just one thing. If each function only does one, reasonably general thing, they can easily be reused and mixed together (composed) to make useful things. Another useful one is “don’t repeat yourself”, so like, any time you see repeated patterns in code (maybe anything that’s copy-pasted more than twice), it should be refactored out into one common function or something.

I still think you’re missing some contexts. When I looked through the spec I saw they were using the phrase “controlling expression” to describe the predicates in if statements, from there I could see they always used the phrase “unequal to 0” or “equal to 0” to describe the comparison. By searching those phrases I was able to come up with the following contexts:

* Unary !
* &&/||
* ?:
* If
* While
* Do
* For
* assert

However, Sam pointed out that C++ also has extra contexts that C doesn’t have. He mentioned cast to Bool. I haven’t checked the C++ spec, but could you give that a search and see what other contexts we might be missing?

Also, it looks like you have some merge conflicts. Have you looked into those at all?

2017-05-02 02:45 UTC, dgopstein commented on src/atom_finder/classifier.clj
> +   (ValidatedAtom :preprocessor-in-statement preprocessor-parent?        all-non-toplevel-preprocessors)
Why are you changing this?

2017-05-02 02:45 UTC, dgopstein commented on src/atom_finder/classifier/implicit-predicate.clj
> +  :else false))
It doesn't look like this function removes parentheses, it looks like applies heuristics to unary operators. If instead you made it actually remove parentheses then you wouldn't need the cyclic reference either, you could just do something like:

(->> node remove-parentheses implicit-expression?)

Also, fix your indentation.

2017-05-02 02:45 UTC, dgopstein commented on test/atom_finder/classifier_test.clj
> +    (test-atom-lines "implicit-predicate.c" "<true>" (default-finder implicit-predicate-atom?)))
Can you add individual tests to test at the node (not line) level? See for example: https://github.com/dgopstein/atom-finder/blob/master/test/atom_finder/classifier_test.clj#L14

Then add a few tests. For example I'm curious what your code says for `!1` and `!1 ? 2 : 3`. In theory I think the first one should be an atom, and the second one shouldn't.

2017-09-28 23:13 UTC, closed without merging